// Title: create_db.js
// Purpose: create the character data table within the swgoh database
// Author: Cameron Kocher

var mysql = require('mysql');

var con = mysql.createConnection({
	host: "localhost",
	user: "hydra314",
	password: "FCNavy46@",
	database: "swgoh"
});

con.connect(function(err){
	if(err) throw err;
	console.log("Connected!");
	var sql = "CREATE TABLE characters (id INT AUTO_INCREMENT PRIMARY KEY,name VARCHAR(50) NOT NULL,alignment ENUM('LS','DS') NOT NULL,rank ENUM('Grand Master','Master','Knight','Padawan','Youngling') NOT NULL,faction SET('Bounty Hunter','Clone Trooper','Droid','Empire','Ewok','First Order','Galactic Republic','Geonosian','Imperial Trooper','Jawa','Jedi','Nightsister','Phoenix','Rebel','Resistance','Scoundrel','Separatist','Sith','Tusken','none') NOT NULL,pic VARCHAR(100))";
	con.query(sql,function(err,result){
		if(err) throw err;
		console.log("Table created");
	});

	var sql_characters = "INSERT INTO characters (name,alignment,rank,faction,pic) VALUES ?";
	var values = [
		['Aayla Secura','LS','Master',('Galactic Republic','Jedi'),'./images/charimages/aayla_secura.png'],
		['Admiral Ackbar','LS','Knight',('Rebel'),'./images/charimages/admiral_ackbar.png'],
		['Ahsoka Tano','LS','Knight',('Galactic Republic','Jedi'),'./images/charimages/ahsoka_tano.png'],
		['Ahsoka Tano (Fulcrum)','LS','Master',('Rebel'),'./images/charimages/fulcrum.png'],
		['Asajj Ventress','DS','Master',('Nightsister','Separatist'),'./images/charimages/asajj_ventress.png'],
		['B2 Super Battle Droid','DS','Master',('Droid','Separatist'),'./images/charimages/b2_super_battle_droid.png'],
		['Barriss Offee','LS','Grand Master',('Galactic Republic','Jedi'),'./images/charimages/barriss_offee.png'],
		['Baze Malbus','LS','Grand Master',('Rebel'),'./images/charimages/baze_malbus.png'],
		['BB-8','LS','Master',('Droid','Resistance'),'./images/charimages/bb-8.png'],
		['Biggs Darklighter','LS','Master',('Rebel'),'./images/charimages/biggs_darklighter.png'],
		['Bistan','LS','Padawan',('Rebel'),'./images/charimages/bistan.png'],
		['Boba Fett','DS','Master',('Bounty Hunter','Scoundrel'),'./images/charimages/boba_fett.png'],
		['Bodhi Rook','LS','Youngling',('Rebel'),'./images/charimages/bodhi_rook.png'],
		['Cad Bane','DS','Youngling',('Bounty Hunter','Scoundrel'),'./images/charimages/cad_bane.png'],
		['Captain Han Solo','LS','Knight',('Rebel','Scoundrel'),'./images/charimages/captain_han_solo.png'],
		['Captain Phasma','DS','Master',('First Order'),'./images/charimages/captain_phasma.png'],
		['Cassian Andor','LS','Knight',('Rebel'),'./images/charimages/cassian_andor.png'],
		['CC-2224 "Cody"','LS','Knight',('Clone Trooper','Galactic Republic'),'./images/charimages/cody.png'],
		['Chief Chirpa','LS','Knight',('Ewok'),'./images/charimages/chief_chirpa.png'],
		['Chief Nebit','LS','Padawan',('Jawa'),'./images/charimages/chief_nebit.png'],
		['Chirrut Imwe','LS','Grand Master',('Rebel'),'./images/charimages/chirrut_imwe.png'],
		['Chopper','LS','Padawan',('Droid','Phoenix','Rebel'),'./images/charimages/chopper.png'],
		['Clone Sergeant - Phase I','LS','Knight',('Clone Trooper','Galactic Republic'),'./images/charimages/clone_sergeant_phase_i.png'],
		['Clone Wars Chewbacca','LS','Youngling',('Galactic Republic','Scoundrel'),'./images/charimages/clone_wars_chewbacca.png'],
		['Colonel Starck','DS','Knight',('Empire','Imperial Trooper'),'./images/charimages/colonel_starck.png'],
		['Commander Luke Skywalker','LS','Grand Master',('Rebel'),'./images/charimages/commander_luke_skywalker.png'],
		['Coruscant Underworld Police','LS','Youngling',('Galactic Republic'),'./images/charimages/coruscant_underworld_police.png'],
		['Count Dooku','DS','Knight',('Separatist','Sith'),'./images/charimages/count_dooku.png'],
		['CT-21-0408 "Echo"','LS','Padawan',('Clone Trooper','Galactic Republic'),'./images/charimages/echo.png'],
		['CT-5555 "Fives"','LS','Knight',('Clone Trooper','Galactic Republic'),'./images/charimages/fives.png'],
		['CT-7567 "Rex"','LS','Grand Master',('Clone Trooper','Galactic Republic'),'./images/charimages/rex.png'],
		['Darth Maul','DS','Master',('Sith'),'./images/charimages/darth_maul.png'],
		['Darth Nihilus','DS','Grand Master',('Sith'),'./images/charimages/darth_nihilus.png'],
		['Darth Sidious','DS','Master',('Sith'),'./images/charimages/darth_sidious.png'],
		['Darth Vader','DS','Master',('Empire','Sith'),'./images/charimages/darth_vader.png'],
		['Dathcha','LS','Padawan',('Jawa'),'./images/charimages/dathcha.png'],
		['Death Trooper','DS','Master',('Empire','Imperial Trooper'),'./images/charimages/death_trooper.png'],
		['Dengar','DS','Youngling',('Bounty Hunter','Scoundrel'),'./images/charimages/dengar.png'],
		['Director Krennic','DS','Master',('Empire'),'./images/charimages/director_krennic.png'],
		['Eeth Koth','LS','Youngling',('Galactic Republic','Jedi'),'./images/charimages/eeth_koth.png'],
		['Emperor Palpatine','DS','Master',('Empire','Sith'),'./images/charimages/emperor_palpatine.png'],
		['Ewok Elder','LS','Knight',('Ewok'),'./images/charimages/ewok_elder.png'],
		['Ewok Scout','LS','Padawan',('Ewok'),'./images/charimages/ewok_scout.png'],
		['Ezra Bridger','LS','Master',('Jedi','Phoenix','Rebel'),'./images/charimages/ezra_bridger.png'],
		['Finn','LS','Knight',('Resistance'),'./images/charimages/finn.png'],
		['First Order Officer','DS','Knight',('First Order'),'./images/charimages/first_order_officer.png'],
		['First Order SF TIE Pilot','DS','Knight',('First Order'),'./images/charimages/first_order_sf_tie_pilot.png'],
		['First Order Stormtrooper','DS','Knight',('First Order'),'./images/charimages/first_order_stormtrooper.png'],
		['First Order TIE Pilot','DS','Master',('First Order'),'./images/charimages/first_order_tie_pilot.png'],
		['Gamorrean Guard','DS','Youngling',('Scoundrel'),'./images/charimages/gamorrean_guard.png'],
		['Gar Saxon','DS','Knight',('Empire'),'./images/charimages/gar_saxon.png'],
		['Garazeb "Zeb" Orrrelios','LS','Knight',('Phoenix','Rebel'),'./images/charimages/zeb.png'],
		['General Grievous','DS','Padawan',('Droid','Separatist'),'./images/charimages/general_grievous.png'],
		['General Kenobi','LS','Grand Master',('Galactic Republic','Jedi'),'./images/charimages/general_kenobi.png'],
		['General Veers','DS','Knight',('Empire','Imperial Trooper'),'./images/charimages/general_veers.png'],
		['Geonosian Soldier','DS','Padawan',('Geonosian','Separatist'),'./images/charimages/geonosian_soldier.png'],
		['Geonosian Spy','DS','Padawan',('Geonosian','Separatist'),'./images/charimages/geonosian_spy.png'],
		['Grand Admiral Thrawn','DS','Grand Master',('Empire'),'./images/charimages/grand_admiral_thrawn.png'],
		['Grand Master Yoda','LS','Master',('Galactic Republic','Jedi'),'./images/charimages/grand_master_yoda.png'],
		['Grand Moff Tarkin','DS','Knight',('Empire'),'./images/charimages/grand_moff_tarkin.png'],
		['Greedo','DS','Youngling',('Bounty Hunter','Scoundrel'),'./images/charimages/greedo.png'],
		['Han Solo','LS','Grand Master',('Rebel','Scoundrel'),'./images/charimages/han_solo.png'],
		['Hera Syndulla','LS','Knight',('Phoenix','Rebel'),'./images/charimages/hera_syndulla.png'],
		['Hermit Yoda','LS','Grand Master',('Jedi'),'./images/charimages/hermit_yoda.png'],
		['HK-47','DS','Knight',('Droid'),'./images/charimages/hk-47.png'],
		['Hoth Rebel Scout','LS','Youngling',('Rebel'),'./images/charimages/hoth_rebel_scout.png'],
		['Hoth Rebel Soldier','LS','Youngling',('Rebel'),'./images/charimages/hoth_rebel_soldier.png'],
		['IG-100 MagnaGuard','DS','Padawan',('Droid','Separatist'),'./images/charimages/ig-100.png'],
		['IG-86 Sentinel Droid','DS','Knight',('Droid'),'./images/charimages/ig-86.png'],
		['IG-88','DS','Master',('Bounty Hunter','Droid','Scoundrel'),'./images/charimages/ig-88.png'],
		['Ima-Gun Di','LS','Padawan',('Galactic Republic','Jedi'),'./images/charimages/ima-gun_di.png'],
		['Imperial Probe Droid','DS','Master',('Droid','Empire'),'./images/charimages/imperial_probe_droid.png'],
		['Imperial Super Commando','DS','Padawan',('Empire'),'./images/charimages/imperial_super_commando.png'],
		['Jawa','LS','Padawan',('Jawa'),'./images/charimages/jawa.png'],
		['Jawa Engineer','LS','Padawan',('Jawa'),'./images/charimages/jawa_engineer.png'],
		['Jawa Scavenger','LS','Padawan',('Jawa'),'./images/charimages/jawa_scavenger.png'],
		['Jedi Consular','LS','Padawan',('Jedi','Galactic Republic'),'./images/charimages/jedi_consular.png'],
		['Jedi Knight Anakin','LS','Master',('Galactic Republic','Jedi'),'./images/charimages/jedi_knight_anakin.png'],
		['Jedi Knight Guardian','LS','Youngling',('Galactic Republic','Jedi'),'./images/charimages/jedi_knight_guardian.png'],
		['Jyn Erso','LS','Master',('Rebel'),'./images/charimages/jyn_erso.png'],
		['K-2SO','LS','Padawan',('Droid','Rebel'),'./images/charimages/k-2so.png'],
		['Kanan Jarrus','LS','Knight',('Jedi','Phoenix','Rebel'),'./images/charimages/kanan_jarrus.png'],
		['Kit Fisto','LS','Padawan',('Galactic Republic','Jedi'),'./images/charimages/kit_fisto.png'],
		['Kylo Ren','DS','Master',('First Order'),'./images/charimages/kylo_ren.png'],
		['Kylo Ren (Unmasked)','DS','Master',('First Order'),'./images/charimages/kylo_ren_unmasked.png'],
		['Lando Calrissian','LS','Master',('Rebel','Scoundrel'),'./images/charimages/lando_calrissian.png'],
		['Lobot','LS','Youngling',('Rebel'),'./images/charimages/lobot.png'],
		['Logray','LS','Knight',('Ewok'),'./images/charimages/logray.png'],
		['Luke Skywalker (Farmboy)','LS','Knight',('Rebel'),'./images/charimages/luke_skywalker_farmboy.png'],
		['Luminara Unduli','LS','Padawan',('Galactic Republic','Jedi'),'./images/charimages/luminara_unduli.png'],
		['Mace Windu','LS','Youngling',('Galactic Republic','Jedi'),'./images/charimages/mace_windu.png'],
		['Magmatrooper','DS','Knight',('Empire','Imperial Trooper'),'./images/charimages/magmatrooper.png'],
		['Mob Enforcer','DS','Youngling',('Scoundrel'),'./images/charimages/mob_enforcer.png'],
		['Mother Talzin','DS','Master',('Nightsister'),'./images/charimages/mother_talzin.png'],
		['Nightsister Acolyte','DS','Knight',('Nightsister'),'./images/charimages/nightsister_acolyte.png'],
		['Nightsister Initiate','DS','Knight',('Nightsister'),'./images/charimages/nightsister_initiate.png'],
		['Nightsister Spirit','DS','Knight',('Nightsister'),'./images/charimages/nightsister_spirit.png'],
		['Nightsister Zombie','DS','Knight',('Nightsister'),'./images/charimages/nightsister_zombie.png'],
		['Nute Gunray','DS','Youngling',('Scoundrel','Separatist'),'./images/charimages/nute_gunray.png'],
		['Obi-Wan Kenobi','LS','Master',('Jedi','Rebel'),'./images/charimages/old_ben.png'],
		['Old Daka','DS','Knight',('Nightsister'),'./images/charimages/old_daka.png'],
		['Pao','LS','Youngling',('Rebel'),'./images/charimages/pao.png'],
		['Paploo','LS','Padawan',('Ewok'),'./images/charimages/paploo.png'],
		['Plo Koon','LS','Padawan',('Galactic Republic','Jedi'),'./images/charimages/plo_koon.png'],
		['Poe Dameron','LS','Master',('Resistance'),'./images/charimages/poe_dameron.png'],
		['Poggle the Lesser','DS','Youngling',('Geonosian','Separatist'),'./images/charimages/poggle_the_lesser.png'],
		['Princess Leia','LS','Master',('Rebel'),'./images/charimages/princess_leia.png'],
		['Qui-Gon Jinn','LS','Master',('Galactic Republic','Jedi'),'./images/charimages/qui-gon_jinn.png'],
		['R2-D2','LS','Grand Master',('Droid','Galactic Republic','Rebel','Resistance'),'./images/charimages/r2-d2.png'],
		['Rebel Officer Leia Organa','LS','Knight',('Rebel'),'./images/charimages/rebel_officer_leia_organa.png'],
		['Resistance Pilot','LS','Knight',('Resistance'),'./images/charimages/resistance_pilot.png'],
		['Resistance Trooper','LS','Knight',('Resistance'),'./images/charimages/resistance_trooper.png'],
		['Rey (Scavenger)','LS','Master',('Resistance'),'./images/charimages/rey_scavenger.png'],
		['Royal Guard','DS','Knight',('Empire'),'./images/charimages/royal_guard.png'],
		['Sabine Wren','LS','Knight',('Phoenix','Rebel'),'./images/charimages/sabine_wren.png'],
		['Savage Opress','DS','Master',('Sith'),'./images/charimages/savage_opress.png'],
		['Scarif Rebel Pathfinder','LS','Padawan',('Rebel'),'./images/charimages/scarif_rebel_pathfinder.png'],
		['Shoretrooper','DS','Master',('Empire','Imperial Trooper'),'./images/charimages/shoretrooper.png'],
		['Sith Assassin','DS','Master',('Sith'),'./images/charimages/sith_assassin.png'],
		['Sith Trooper','DS','Knight',('Sith'),'./images/charimages/sith_trooper.png'],
		['Snowtrooper','DS','Knight',('Empire','Imperial Trooper'),'./images/charimages/snowtrooper.png'],
		['Stormtrooper','DS','Knight',('Empire','Imperial Trooper'),'./images/charimages/stormtrooper.png'],
		['Stormtrooper Han','LS','Master',('Rebel','Scoundrel'),'./images/charimages/stormtrooper_han.png'],
		['Sun Fac','DS','Knight',('Geonosian','Separatist'),'./images/charimages/sun_fac.png'],
		['Talia','DS','Youngling',('Nightsister'),'./images/charimages/talia.png'],
		['Teebo','LS','Knight',('Ewok'),'./images/charimages/teebo.png'],
		['TIE Fighter Pilot','DS','Master',('Empire'),'./images/charimages/tie_fighter_pilot.png'],
		['Tusken Raider','DS','Youngling',('Tusken'),'./images/charimages/tusken_raider.png'],
		['Tusken Shaman','DS','Padawan',('Tusken'),'./images/charimages/tusken_shaman.png'],
		['Ugnaught','LS','Youngling',('none'),'./images/charimages/ugnaught.png'],
		['URoRRuRRR','DS','Youngling',('Tusken'),'./images/charimages/uror.png'],
		['Veteran Smuggler Chewbacca','LS','Knight',('Scoundrel'),'./images/charimages/veteran_smuggler_chewbacca.png'],
		['Veteran Smuggler Han Solo','LS','Knight',('Scoundrel'),'./images/charimages/veteran_smuggler_han_solo.png'],
		['Wampa','DS','Grand Master',('none'),'./images/charimages/wampa.png'],
		['Wedge Antilles','LS','Master',('Rebel'),'./images/charimages/wedge_antilles.png'],
		['Wicket','LS','Knight',('Ewok'),'./images/charimages/wicket.png'],
		['Zam Wesell','DS','Padawan',('Bounty Hunter','Scoundrel'),'./images/charimages/zam_wesell.png']
	];

	con.query(sql_characters,[values],function(err,result){
		if(err) throw err;
		console.log("Number of records inserted: " + result.affectedRows);
	});
});